
# Tranformação

## Tabela de paciente

O script descrito a seguir cria tabela temporaria de paciente.

- **nu_ano_nascimento**: calcula o ano de nascimento com base na idade e no mês do registro
- **qt_regitros**: número de registros, o qual será usado para estabelecer qual é o sexo e a idade mais frequente
- **co_prontuario**: número sequencial conforme o mais frequente

```{sql , eval = FALSE}
create table db_sabeis.tm_paciente as
select 
   co_cns_paciente,
   sg_sexo_paciente,
   co_ibge_paciente,
   extract(year from (to_date(nu_competencia::text, 'YYYYMM')))::int-nu_idade_paciente as nu_ano_nascimento,
   count(*) as qt_regitros,
   DENSE_RANK() OVER(PARTITION by co_cns_paciente ORDER BY count(*) desc) as co_prontuario
  from db_sabeis.tf_apac_medicamento
 where co_cns_paciente > 0
 group by 1,2,3,4;

CREATE INDEX tm_paciente__co_cns_paciente_idx 
          ON db_sabeis.tm_paciente (co_cns_paciente);
```

Obtem os registros menos frequentes de sexo, município e idade.

```{sql , eval = FALSE}
create table db_sabeis.tm_paciente2 as
select * from db_sabeis.tm_paciente where co_prontuario > 1 order by 1;

CREATE INDEX tm_paciente2__co_cns_paciente_idx 
          ON db_sabeis.tm_paciente2 (co_cns_paciente);
```

Valida, ao assinalar com "1", os registros menos frequentes em que 

-- o município e o sexo são iguais
-- o ano de nascimento difere em um ano relativo ao mais frequente.

```{sql , eval = FALSE}
update db_sabeis.tm_paciente2 A
   set co_prontuario=1
  from db_sabeis.tm_paciente B
 where A.co_cns_paciente=B.co_cns_paciente
   and A.nu_ano_nascimento=B.nu_ano_nascimento-1
   and A.sg_sexo_paciente=B.sg_sexo_paciente
   and A.co_ibge_paciente=B.co_ibge_paciente;
```

```{sql , eval = FALSE}
update db_sabeis.tm_paciente2 A
   set co_prontuario=1
  from db_sabeis.tm_paciente B
 where A.co_cns_paciente=B.co_cns_paciente
   and A.nu_ano_nascimento=B.nu_ano_nascimento+1
   and A.sg_sexo_paciente=B.sg_sexo_paciente
   and A.co_ibge_paciente=B.co_ibge_paciente;
```

Valida, ao assinalar com "1", os registros em que 
ano de nascimento e sexo equivalam, 
desconsiderando o município.

```{sql , eval = FALSE}
update db_sabeis.tm_paciente2 A
   set co_prontuario=1
  from db_sabeis.tm_paciente B
 where A.co_cns_paciente=B.co_cns_paciente
   and A.nu_ano_nascimento=B.nu_ano_nascimento
   and A.sg_sexo_paciente=B.sg_sexo_paciente;
```

Invalida, assinalando com "0", os registros em que não houve equivalência de

- município, sexo e diferença de um no ano de nascimento 
- sexo e ano de nascimento exato

```{sql , eval = FALSE}
update db_sabeis.tm_paciente A
   set co_prontuario=0
  from db_sabeis.tm_paciente2 B
 where A.co_cns_paciente=B.co_cns_paciente
   and B.co_prontuario>1
   and A.co_prontuario>1;
```

Cria a tabela definitiva de paciente.

```{sql , eval = FALSE}
create table db_sabeis.tf_paciente as
select * from db_sabeis.tm_paciente 
 where co_prontuario=1
 order by 1;  
  
CREATE INDEX tf_paciente__co_cns_paciente_idx 
          ON db_sabeis.tf_paciente (co_cns_paciente);

```


## Evento diagnóstico

O script a seguir cria a tabela de evento de diagnóstico.

Ao final é criada uma tabela com o 

- CID10, seja primário ou secundário
- primeira data de diagnóstico
- última data de diagnóstico
- diferença de tempoem meses
- número de aparições do diagnóstico em registro administrativo

```{sql , eval = FALSE}
create table db_sabeis.tm_evento as
select 
 B.co_cns_paciente,
 co_sigtap_procedimento,
 min(A.nu_competencia) as nu_competencia_min,
 max(A.nu_competencia) as nu_competencia_max,
 round(extract(year from age(to_date(max(nu_competencia)::text, 'YYYYMM'),to_date(min(nu_competencia)::text, 'YYYYMM'))) * 12 +
extract(month from age(to_date(max(nu_competencia)::text, 'YYYYMM'),to_date(min(nu_competencia)::text, 'YYYYMM')))+1)::int as qt_meses,
 count(*) as qt_registros,
 sum(st_obito_paciente) as st_obito_paciente
 from 
 db_sabeis.tf_apac_medicamento A,
 db_sabeis.tf_paciente B
where A.co_cns_paciente=B.co_cns_paciente
   and A.sg_sexo_paciente=B.sg_sexo_paciente
   and extract(year from (to_date(nu_competencia::text, 'YYYYMM')))::int-nu_idade_paciente between B.nu_ano_nascimento-1 and B.nu_ano_nascimento+1 
   and A.qt_aprovada > 0
   and co_cid10_diagnostico_principal is not null
group by 1,2;   
```

```{sql , eval = FALSE}
insert into db_sabeis.tm_evento
select 
 B.co_cns_paciente,
 A.co_cid10_diagnostico_secundario,
 min(A.nu_competencia) as nu_competencia_min,
 max(A.nu_competencia) as nu_competencia_max,
 round(extract(year from age(to_date(max(nu_competencia)::text, 'YYYYMM'),to_date(min(nu_competencia)::text, 'YYYYMM'))) * 12 +
extract(month from age(to_date(max(nu_competencia)::text, 'YYYYMM'),to_date(min(nu_competencia)::text, 'YYYYMM')))+1)::int as qt_meses,
 count(*) as qt_registros,
 sum(st_obito_paciente) as st_obito_paciente
 from 
 db_sabeis.tf_apac_medicamento A,
 db_sabeis.tf_paciente B
where A.co_cns_paciente=B.co_cns_paciente
   and A.sg_sexo_paciente=B.sg_sexo_paciente
   and extract(year from (to_date(nu_competencia::text, 'YYYYMM')))::int-nu_idade_paciente between B.nu_ano_nascimento-1 and B.nu_ano_nascimento+1 
   and A.qt_aprovada > 0
   and co_cid10_diagnostico_secundario is not null
group by 1,2;
```

```{sql , eval = FALSE}         
create table db_sabeis.tm_evento_cid as
select 
 co_cns_paciente,
 co_cid10_diagnostico_principal,
 min(nu_competencia_min) as nu_competencia_min,
 max(nu_competencia_max) as nu_competencia_max,
 round(extract(year from age(to_date(max(nu_competencia_max)::text, 'YYYYMM'),to_date(min(nu_competencia_min)::text, 'YYYYMM'))) * 12 +
extract(month from age(to_date(max(nu_competencia_max)::text, 'YYYYMM'),to_date(min(nu_competencia_min)::text, 'YYYYMM')))+1)::int as qt_meses,
 sum(qt_registros) as qt_registros,
 sum(st_obito_paciente) as st_obito_paciente
from db_sabeis.tm_evento
group by 1,2;

```

## Evento tratamento

O tratamento não é definido como o diagnóstico, pois implica em verificar
períodos em que há descontinuidade.

A seguir é mostrada uma iteração para um medicamento que possui dois códigos
SIGTAP.

São elencados apenas os registros com 
CNS válido e quantidade aprovada maior que zero.

Ao final é criada uma tabela com o 

- medicamento
- primeira data de tratamento contínuo
- última data de tratamento contínuo
- código sequencial do tratamento contínuo
- diferença de tempoem meses
- número de aparições do em registro administrativo
- soma da quantidade aprovada no período
- soma valor reportado em reais


```{sql , eval=FALSE}
drop table if exists db_sabeis.tm_evento, db_sabeis.tm_evento_1, db_sabeis.tf_evento_medicamento1;

create table db_sabeis.tm_evento as
select 
      B.co_cns_paciente,
      nu_competencia,
      STRING_AGG (distinct co_cid10_diagnostico_principal, ',') as co_cid10_diagnostico_principal,
      STRING_AGG (distinct co_cnes_estabelecimento::text, ',') as co_cnes_estabelecimento,
      STRING_AGG (distinct co_ibge_gestao::text, ',') as co_ibge_gestao,
      DENSE_RANK() OVER(
         PARTITION by B.co_cns_paciente ORDER BY nu_competencia
         ) as co_seq_tratamento,
	count(*) as qt_registros,
      sum(A.qt_aprovada) as qt_aprovada,
      sum(A.vl_aprovado) as vl_aprovado,
      sum(st_obito_paciente) as st_obito_paciente
 from 
      db_sabeis.tf_apac_medicamento A,
      db_sabeis.tf_paciente B
where A.co_cns_paciente=B.co_cns_paciente
  and A.sg_sexo_paciente=B.sg_sexo_paciente
  and extract(year from (to_date(nu_competencia::text, 'YYYYMM')))::int-nu_idade_paciente between B.nu_ano_nascimento-1 and B.nu_ano_nascimento+1 
  and A.qt_aprovada > 0
  and A.co_sigtap_procedimento in (SIGTAP)
group by 1,2
order by 1,2;   


CREATE INDEX tm_evento__co_cns_paciente_idx 
          ON db_sabeis.tm_evento (co_cns_paciente);
```

Agora defini-se, para cada CNS, 
qual registro tem diferença de mais de um mês em relação ao anterior.

```{sql , eval = FALSE}         
create table db_sabeis.tm_evento_1 as         
select 
  co_cns_paciente,
  delta as co_seq_tratamento
from
(
select 
  A.co_cns_paciente,
  A.co_seq_tratamento,
  B.nu_competencia,
  case 
    when to_date(B.nu_competencia::text, 'YYYYMM')-to_date(A.nu_competencia::text, 'YYYYMM') > 31 then A.co_seq_tratamento
    when A.co_seq_tratamento = 1 then A.co_seq_tratamento
    else 0 end as delta
 from db_sabeis.tm_evento A,
      db_sabeis.tm_evento B
where A.co_cns_paciente=B.co_cns_paciente
  and A.co_seq_tratamento=B.co_seq_tratamento-1
  ) X
where delta > 0;  

CREATE INDEX tm_evento1__co_cns_paciente_idx 
          ON db_sabeis.tm_evento_1 (co_cns_paciente);
```

Aqui é assinalado o código sequencial do registro em que há descontinuidade
de pelo menos um mês.

```{sql , eval = FALSE}         
alter table db_sabeis.tm_evento add co_tratamento smallint default null;         

update db_sabeis.tm_evento set co_tratamento = 2;

update db_sabeis.tm_evento A
   set co_tratamento=B.co_seq_tratamento+1
  from db_sabeis.tm_evento_1 B   
 where A.co_cns_paciente=B.co_cns_paciente
   and A.co_seq_tratamento > B.co_seq_tratamento   ;
```

Cria-se outra tabela temporária para inserir

- **co_seq_tratamento** o identificador sequencial de cada tratamento contínuio,
para cada CNS.
- validade do período de tratamento segundo cálculo de discrepância com 
intervalo interquartílico IQR.
- validade do período de tratamento segundo cálculo de discrepância com 
intervalo interquartílico IQR segundo a secretaria (discrepância devido a acesso).
- código do PCDT.



```{sql , eval=FALSE}
create table db_sabeis.tf_evento_medicamento1 as 
select 
 co_cns_paciente,
 'ABREV' as sg_procedimento,
 STRING_AGG (distinct co_cid10_diagnostico_principal, ',') as co_cid10_diagnostico_principal,
 STRING_AGG (distinct co_cnes_estabelecimento::text, ',') as co_cnes_estabelecimento,
 STRING_AGG (distinct co_ibge_gestao::text, ',') as co_ibge_gestao,
 min(nu_competencia) as nu_competencia_min,
 max(nu_competencia) as nu_competencia_max,
 round(extract(year from age(to_date(max(nu_competencia)::text, 'YYYYMM'),to_date(min(nu_competencia)::text, 'YYYYMM'))) * 12 +
extract(month from age(to_date(max(nu_competencia)::text, 'YYYYMM'),to_date(min(nu_competencia)::text, 'YYYYMM')))+1)::int as qt_meses,
 sum(qt_registros) as qt_registros,
       DENSE_RANK() OVER(
         PARTITION by co_cns_paciente ORDER BY co_tratamento
         ) as co_seq_tratamento,
      sum(qt_aprovada) as qt_aprovada,
      sum(vl_aprovado) as vl_aprovado,
      sum(st_obito_paciente) as st_obito_paciente
from db_sabeis.tm_evento
group by 1,co_tratamento
order by 1,3;

alter table db_sabeis.tf_evento_medicamento1 
  add st_qt_meses_valido_iqr smallint default 0,
  add st_qt_meses_valido_gestao_iqr smallint default 0,
  add co_pcdt smallint default 0;
```

Estabelece discrepância segundo o período de tratamento.

```{sql , eval=FALSE}
update 
   db_sabeis.tf_evento_medicamento1 A
   set st_qt_meses_valido_iqr = 1
from (   
select 
  sg_procedimento,
  percentile_disc(0.5) within group (order by qt_meses) - (percentile_disc(0.75) within group (order by qt_meses) - percentile_disc(0.25) within group (order by qt_meses))*1.5 as iqrmin,
  percentile_disc(0.5) within group (order by qt_meses) + (percentile_disc(0.75) within group (order by qt_meses) - percentile_disc(0.25) within group (order by qt_meses))*1.5 as iqrmax
 from db_sabeis.tf_evento_medicamento1 
 group by sg_procedimento
) B
where qt_meses between iqrmin and iqrmax;
```

Estabelece discrepância segundo o período de tratamento por secretaria.

```{sql , eval=FALSE}
update 
   db_sabeis.tf_evento_medicamento1 A
   set st_qt_meses_valido_gestao_iqr = 1
from (   
select 
  case 
         when co_ibge_gestao like '%,%'
         then substring(
           co_ibge_gestao, 1, 
           POSITION(',' in co_ibge_gestao)-1) 
    else co_ibge_gestao end as co_ibge_gestao,
  percentile_disc(0.5) within group (order by qt_meses) - (percentile_disc(0.75) within group (order by qt_meses) - percentile_disc(0.25) within group (order by qt_meses))*1.5 as iqrmin,
  percentile_disc(0.5) within group (order by qt_meses) + (percentile_disc(0.75) within group (order by qt_meses) - percentile_disc(0.25) within group (order by qt_meses))*1.5 as iqrmax
 from db_sabeis.tf_evento_medicamento1 
 group by 1
) B
where qt_meses between iqrmin and iqrmax
and case 
         when A.co_ibge_gestao like '%,%'
         then substring(
           A.co_ibge_gestao, 1, 
           POSITION(',' in A.co_ibge_gestao)-1) 
    else A.co_ibge_gestao end = B.co_ibge_gestao;
```


Atualiza o código do PCDT segundo o medicamento e a doença.

```{sql , eval=FALSE}
update db_sabeis.tf_evento_medicamento1 A
   set co_pcdt=B.co_pcdt
  from db_sabeis.td_pcdt_cid_sigtap B
 where B.co_sigtap_procedimento in (SIGTAP)
   and B.co_cid10_diagnostico_principal = 
       case 
         when A.co_cid10_diagnostico_principal like '%,%'
         then substring(
           A.co_cid10_diagnostico_principal, 1, 
           POSITION(',' in A.co_cid10_diagnostico_principal)-1) 
    else A.co_cid10_diagnostico_principal end;
```


Insere os registros na tabela fato definitiva.

```{sql , eval = FALSE}
insert into db_sabeis.tf_evento_medicamento
select * from db_sabeis.tf_evento_medicamento1
order by co_cns_paciente, co_pcdt, co_seq_tratamento;

drop table if exists db_sabeis.tm_evento, db_sabeis.tm_evento_1, db_sabeis.tf_evento_medicamento1;
```


```{bash, eval=FALSE}
echo "drop table if exists db_sabeis.tf_evento_medicamento;
CREATE TABLE db_sabeis.tf_evento_medicamento (
	co_cns_paciente int8 NULL,
	sg_procedimento varchar(15) NULL,
	co_cid10_diagnostico_principal varchar(150) NULL,
	co_cnes_estabelecimento  varchar(150) NULL,
	co_ibge_gestao  varchar(150) NULL,
	nu_competencia_min int4 NULL,
	nu_competencia_max int4 NULL,
	qt_meses int4 NULL,
	qt_registros int4 NULL,
	co_seq_tratamento int8 NULL,
	qt_aprovada int8 NULL,
	vl_aprovado numeric NULL,
	st_obito_paciente int4 null,
  st_qt_meses_valido_iqr int4 default 0,
  st_qt_meses_valido_gestao_iqr int4 default 0,
  co_pcdt int4 default 0
);" > ~/Dropbox/sabeis/source/tratamento.completo.sql;
for line in $(cat ~/Dropbox/sabeis/dataset/abrev.csv);do  cat ~/Dropbox/sabeis/source/tratamento.sql | sed "s/ABREV/$(echo $line | awk -F'£' '{print $1}')/g" | sed "s/SIGTAP/$(echo $line | awk -F'£' '{print $2}'| sed 's/,/, /g' )/g" >>  ~/Dropbox/sabeis/source/tratamento.completo.sql; done
```

