### Pirâmide etária - Usuários ao mês por habitante segundo o PCDT


#### Conceituação
#### Interpretação
#### Usos
#### Limitações
#### Fonte
#### Métodos de Cálculo
#### Categorias Sugeridas para Análise
#### Dados Estatísticos e Comentários
#### Notas

#### Conjunto de dados e Código-fonte

Baixe o arquivo 
[csv](https://www.dropbox.com/s/3pvxxfg3hz4a82h/db_sabeis.tf_pcdt_paciente.csv?dl=0) 
contido na pasta *dataset*.


```{r}
library(pyramid)
library(knitr)
```

```{r}
tf_pcdt_paciente = read.csv(file = '../dataset/db_sabeis.tf_pcdt_paciente.csv')

# ajusta para o formato percentual
tf_pcdt_paciente$qt_paciente_m = 
  tf_pcdt_paciente$qt_paciente_m/tf_pcdt_paciente$qt_registros_pcdt*100

tf_pcdt_paciente$qt_paciente_f = 
  tf_pcdt_paciente$qt_paciente_f/tf_pcdt_paciente$qt_registros_pcdt*100
```

```{r echo=FALSE}
kable(
  tf_pcdt_paciente[9:13,c(2,3,6)], 
  caption = "Amostra da tabela de entrada."
)
```

```{r}
pyramid(
      subset(tf_pcdt_paciente, co_pcdt == 10)[,c(2,3,6)],
      Llab="Masculino",Rlab="Feminino",
      Lcol="navy",
      Ldens=5,
      Rcol="red",
      Rdens=10, GL=FALSE, Clab = "Idade", main = "usuários (%)"
    )

```


